const GET_FROM_AIRPORTS_SUCCESS = 'GET_FROM_AIRPORTS_SUCCESS';
const GET_TO_AIRPORTS_SUCCESS = 'GET_TO_AIRPORTS_SUCCESS';
const CLEAR_FROM_AIRPORTS = 'CLEAR_FROM_AIRPORTS';
const CLEAR_TO_AIRPORTS = 'CLEAR_TO_AIRPORTS';

export {
    GET_FROM_AIRPORTS_SUCCESS,
    GET_TO_AIRPORTS_SUCCESS,
    CLEAR_FROM_AIRPORTS,
    CLEAR_TO_AIRPORTS
};